### ISSUE TITLE
Feature request: config files with contexts only

### ISSUE THREAD

**Issue by reinoud** [sbstp/kubie#124]
Hi,

we use a cluster with a lot of namespace, and I would like to use a separate context for each.

I have a config file downloaded from Rancher, that defines the cluster, user and a single context. This file obviously contains my private token

I would like to use a separate config with only additional contexts defined. We would like to maintain this file centrally, so all Kubernetes admins can git pull this file to have all context definitions updated.

When I try this now, kubie complains:

` contexts.yml: missing field `clusters` at line 4 column 9 `

since it is not a complete config file.

The contexts.yml file looks like this:

```
---
# list of all cluster-namespace combinations for cluster production

contexts:
- name: "production-namespace1"
  context:
    user: "myuser"
    cluster: "production"
    namespace: "namespace1"

- name: "production-namespace2"
  context:
    user: "myuser"
    cluster: "production"
    namespace: "namespace2"

- name: "production-namespace3"
  context:
    user: "myuser"
    cluster: "production"
    namespace: "namespace3"
```

The use-case here is that we do not have rights on the cluster to get all namespaces, so selecting a context with a set namespace makes our life much easier.
