### ISSUE TITLE
`invalid type` when loading null values from config when clusters is null

### ISSUE THREAD

**Issue by giggio** [sbstp/kubie#171]
I have several config files, and the following `~/.kube/config`:

```yml
apiVersion: v1
clusters: null
contexts: null
current-context: cluster1
kind: Config
preferences: {}
users: null
```

Kubie fails with:

```
Error loading kubeconfig /home/user/.kube/config: clusters: invalid type: unit value, expected a sequence at line 2 column 11
Error: Could not find any contexts in the Kubie kubeconfig directories!
```
